# Generated by Django 3.0.7 on 2023-11-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_receiptproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptproduct',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='receipt',
            name='tprice',
            field=models.IntegerField(default=0),
        ),
    ]
